"""
model_selector.py

Model selection module for ArchForge.

Responsibilities
----------------
1. Read dataset profiling metadata.
2. Determine suitable candidate models.
3. Filter unsuitable models.
4. Respect dataset training safety determined by DatasetProfiler.
5. Ask for user confirmation only when training is unsafe.

Important
---------
DatasetProfiler is responsible for determining whether the dataset
is safe for automated training.

ModelSelector is responsible for deciding which models are suitable.

ModelSelector MUST NOT independently override the profiler's
training safety decision.
"""

from pathlib import Path
from typing import Dict, Any, List


class ModelSelector:
    """
    Select appropriate machine learning models based on
    dataset characteristics.
    """

    # ============================================================
    # Initialization
    # ============================================================

    def __init__(
        self,
        project_root: Path,
    ) -> None:

        self.project_root = Path(
            project_root
        ).resolve()

    # ============================================================
    # Main Model Selection
    # ============================================================

    def select_models(
        self,
        dataset_profile: Dict[str, Any],
    ) -> Dict[str, Any]:
        """
        Select appropriate models using the dataset profile.

        Parameters
        ----------
        dataset_profile : Dict[str, Any]
            Output generated by DatasetProfiler.profile().

        Returns
        -------
        Dict[str, Any]
            Model selection result.
        """

        if not dataset_profile:

            raise ValueError(
                "Dataset profile cannot be empty."
            )

        print(
            "\n"
            + "=" * 60
        )

        print(
            "MODEL SELECTION"
        )

        print(
            "=" * 60
        )

        # ========================================================
        # Read Dataset Profile
        # ========================================================

        problem_type = dataset_profile.get(
            "problem_type"
        )

        rows = int(
            dataset_profile.get(
                "rows",
                0,
            )
        )

        feature_count = int(
            dataset_profile.get(
                "features",
                0,
            )
        )

        numerical_count = int(
            dataset_profile.get(
                "numerical_feature_count",
                0,
            )
        )

        categorical_count = int(
            dataset_profile.get(
                "categorical_feature_count",
                0,
            )
        )

        dataset_size = dataset_profile.get(
            "dataset_size",
            "unknown",
        )

        dimensionality = dataset_profile.get(
            "dimensionality",
            "unknown",
        )

        target_unique_values = int(
            dataset_profile.get(
                "target_unique_values",
                0,
            )
        )

        # ========================================================
        # IMPORTANT
        # ========================================================
        #
        # Training safety comes DIRECTLY from DatasetProfiler.
        #
        # Do not recalculate safety here.
        #
        # ========================================================

        training_safe = bool(
            dataset_profile.get(
                "training_safe",
                False,
            )
        )

        training_recommendation = (
            dataset_profile.get(
                "training_recommendation",
                "UNSAFE",
            )
        )

        # ========================================================
        # Display Dataset Characteristics
        # ========================================================

        print(
            "\nDataset characteristics:"
        )

        print(
            f"  Problem type          : "
            f"{problem_type}"
        )

        print(
            f"  Rows                  : "
            f"{rows}"
        )

        print(
            f"  Features              : "
            f"{feature_count}"
        )

        print(
            f"  Numerical features    : "
            f"{numerical_count}"
        )

        print(
            f"  Categorical features  : "
            f"{categorical_count}"
        )

        print(
            f"  Dataset size          : "
            f"{dataset_size}"
        )

        print(
            f"  Dimensionality        : "
            f"{dimensionality}"
        )

        print(
            f"  Target unique values  : "
            f"{target_unique_values}"
        )

        # ========================================================
        # Validate Problem Type
        # ========================================================

        if problem_type not in {
            "REGRESSION",
            "CLASSIFICATION",
        }:

            raise ValueError(
                f"Unsupported problem type: "
                f"{problem_type}"
            )

        # ========================================================
        # Candidate Models
        # ========================================================

        if problem_type == "REGRESSION":

            candidate_models = (
                self._regression_models()
            )

        else:

            candidate_models = (
                self._classification_models()
            )

        # ========================================================
        # Filter Models
        # ========================================================

        selected_models = []

        filtered_models = []

        filtering_reasons = {}

        for model_name in candidate_models:

            allowed, reason = (
                self._is_model_suitable(
                    model_name=model_name,
                    rows=rows,
                    feature_count=feature_count,
                    numerical_count=numerical_count,
                    categorical_count=categorical_count,
                    dataset_size=dataset_size,
                    dimensionality=dimensionality,
                    problem_type=problem_type,
                )
            )

            if allowed:

                selected_models.append(
                    model_name
                )

            else:

                filtered_models.append(
                    model_name
                )

                filtering_reasons[
                    model_name
                ] = reason

        # ========================================================
        # Safety Handling
        # ========================================================

        training_allowed = training_safe

        # --------------------------------------------------------
        # If profiler says unsafe:
        #
        # Ask the user whether they want to continue.
        # --------------------------------------------------------

        if not training_safe:

            print(
                "\n"
                + "!" * 60
            )

            print(
                "WARNING"
            )

            print(
                "!" * 60
            )

            print(
                "\n"
                "Dataset profiling has determined that "
                "this dataset is unsafe for reliable "
                "automatic model training."
            )

            print(
                "\n"
                f"Reason: "
                f"{training_recommendation}"
            )

            print(
                "\n"
                "Model performance may be unreliable."
            )

            print(
                "\n"
                "Recommended approach:"
            )

            print(
                "  • Use the simplest available model."
            )

            print(
                "  • Treat the result as experimental."
            )

            print(
                "  • Collect more training data if possible."
            )

            # ----------------------------------------------------
            # Automatically restrict unsafe datasets to the
            # simplest suitable model.
            # ----------------------------------------------------

            simple_model = (
                self._get_simplest_model(
                    problem_type
                )
            )

            if (
                simple_model
                in selected_models
            ):

                selected_models = [
                    simple_model
                ]

            else:

                selected_models = (
                    selected_models[:1]
                )

            # ----------------------------------------------------
            # Ask user
            # ----------------------------------------------------

            try:

                response = input(
                    "\n"
                    "Do you still want to proceed "
                    "with automatic model training? "
                    "(y/N): "
                )

                response = (
                    response
                    .strip()
                    .lower()
                )

                if response == "y":

                    training_allowed = True

                    print(
                        "\nUser selected YES."
                    )

                    print(
                        "Proceeding with the "
                        "recommended model."
                    )

                else:

                    training_allowed = False

                    print(
                        "\nUser selected NO."
                    )

                    print(
                        "Automatic model training "
                        "will be skipped."
                    )

            except EOFError:

                training_allowed = False

                print(
                    "\nNo confirmation received."
                )

                print(
                    "Automatic model training "
                    "will be skipped."
                )

        # ========================================================
        # Safe Dataset
        # ========================================================

        else:

            print(
                "\n"
                "Training safety      : SAFE"
            )

            print(
                "Training allowed     : True"
            )

        # ========================================================
        # Ensure At Least One Model
        # ========================================================

        if not selected_models:

            raise ValueError(
                "No suitable machine learning models "
                "were found for this dataset."
            )

        # ========================================================
        # Display Result
        # ========================================================

        print(
            "\n"
            + "=" * 60
        )

        print(
            "MODEL SELECTION RESULT"
        )

        print(
            "=" * 60
        )

        if len(selected_models) == 1:

            print(
                "\nRecommended model:"
            )

        else:

            print(
                "\nSelected models:"
            )

        for model_name in selected_models:

            print(
                f"  • {model_name}"
            )

        if filtered_models:

            print(
                "\nOther models filtered:"
            )

            for model_name in filtered_models:

                print(
                    f"  • {model_name}"
                )

        print(
            f"\nTraining safety       : "
            f"{'SAFE' if training_safe else 'UNSAFE'}"
        )

        print(
            f"Training allowed      : "
            f"{training_allowed}"
        )

        print(
            "\nModel selection completed."
        )

        # ========================================================
        # Return Result
        # ========================================================

        return {

            "selected_models":
                selected_models,

            "filtered_models":
                filtered_models,

            "filtering_reasons":
                filtering_reasons,

            "recommended_model":
                selected_models[0],

            "training_safe":
                training_safe,

            "training_allowed":
                training_allowed,

            "problem_type":
                problem_type,

            "dataset_profile":
                dataset_profile,
        }

    # ============================================================
    # Regression Models
    # ============================================================

    @staticmethod
    def _regression_models() -> List[str]:
        """
        Return all supported regression models.

        These are candidates only.
        The selector decides which ones are appropriate.
        """

        return [

            "LinearRegression",

            "Ridge",

            "Lasso",

            "ElasticNet",

            "DecisionTreeRegressor",

            "RandomForestRegressor",

            "XGBRegressor",

            "CatBoostRegressor",
        ]

    # ============================================================
    # Classification Models
    # ============================================================

    @staticmethod
    def _classification_models() -> List[str]:
        """
        Return all supported classification models.
        """

        return [

            "LogisticRegression",

            "RidgeClassifier",

            "DecisionTreeClassifier",

            "RandomForestClassifier",

            "XGBClassifier",

            "CatBoostClassifier",
        ]

    # ============================================================
    # Model Suitability
    # ============================================================

    @staticmethod
    def _is_model_suitable(
        model_name: str,
        rows: int,
        feature_count: int,
        numerical_count: int,
        categorical_count: int,
        dataset_size: str,
        dimensionality: str,
        problem_type: str,
    ):
        """
        Determine whether a model should be considered.

        IMPORTANT:
        This method evaluates model suitability only.

        It does NOT determine training safety.
        """

        # ========================================================
        # VERY SMALL DATA
        # ========================================================

        if rows < 20:

            if model_name in {
                "LinearRegression",
                "LogisticRegression",
            }:

                return (
                    True,
                    "Simple baseline model."
                )

            return (
                False,
                "Dataset is extremely small; "
                "complex model is unnecessary."
            )

        # ========================================================
        # LOW-DIMENSIONAL DATA
        # ========================================================

        if dimensionality == "low":

            # ----------------------------------------------------
            # Linear models remain useful as baselines.
            # ----------------------------------------------------

            if model_name in {
                "LinearRegression",
                "Ridge",
                "Lasso",
                "ElasticNet",
            }:

                return (
                    True,
                    "Suitable for low-dimensional data."
                )

        # ========================================================
        # SMALL DATASETS
        # ========================================================

        if rows < 500:

            if model_name in {
                "XGBRegressor",
                "XGBClassifier",
                "CatBoostRegressor",
                "CatBoostClassifier",
            }:

                return (
                    False,
                    "Boosting model may be unnecessary "
                    "for a small dataset."
                )

        # ========================================================
        # HIGH DIMENSIONAL DATA
        # ========================================================

        if dimensionality in {
            "high",
            "extreme",
        }:

            if model_name in {
                "DecisionTreeRegressor",
                "DecisionTreeClassifier",
            }:

                return (
                    False,
                    "Single decision tree may "
                    "overfit high-dimensional data."
                )

        # ========================================================
        # CATEGORICAL DATA
        # ========================================================

        if categorical_count > 0:

            # CatBoost is particularly useful when
            # categorical variables are present.

            if model_name in {
                "CatBoostRegressor",
                "CatBoostClassifier",
            }:

                return (
                    True,
                    "Supports datasets with "
                    "categorical features."
                )

        # ========================================================
        # MEDIUM DATASETS
        # ========================================================

        if rows >= 500:

            if model_name in {
                "RandomForestRegressor",
                "RandomForestClassifier",
                "GradientBoostingRegressor",
                "GradientBoostingClassifier",
            }:

                return (
                    True,
                    "Suitable for medium-sized data."
                )

        # ========================================================
        # LARGE DATASETS
        # ========================================================

        if rows >= 1000:

            if model_name in {
                "XGBRegressor",
                "XGBClassifier",
                "CatBoostRegressor",
                "CatBoostClassifier",
            }:

                return (
                    True,
                    "Suitable for sufficiently large data."
                )

        # ========================================================
        # Default
        # ========================================================

        return (
            True,
            "No filtering rule applied."
        )

    # ============================================================
    # Simplest Model
    # ============================================================

    @staticmethod
    def _get_simplest_model(
        problem_type: str,
    ) -> str:
        """
        Return the simplest baseline model.
        """

        if problem_type == "REGRESSION":

            return "LinearRegression"

        return "LogisticRegression"